stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/interim

  feature_engineering:
    cmd: python -m src.features.feature_engineering
    deps:
    - data/interim
    - src/features/feature_engineering.py
    - src/config/config_loader.py
    
    params:
    - feature_engineering.vectorizer
    - feature_engineering.max_features
    - feature_engineering.lowercase
    - feature_engineering.stop_words
    - feature_engineering.ngram_range
    
    outs:
    - data/processed
    - artifacts/vectorizer.pkl

  model_building:
    cmd: python -m src.model.model_building

    deps:
      - data/processed
      - src/model/model_building.py
      - src/model/model_factory.py
      - src/config/config_loader.py

    params:
      - model.algorithm
      - model.logistic_regression.C
      - model.logistic_regression.solver
      - model.logistic_regression.penalty
      - model.logistic_regression.max_iter

    outs:
      - artifacts/model.pkl

  model_evaluation:
    cmd: python -m src.model.model_evaluation

    deps:
      - artifacts/model.pkl
      - data/processed
      - src/model/model_evaluation.py
      - src/config/config_loader.py

    params:
      - model.algorithm
      - feature_engineering.vectorizer
      - feature_engineering.max_features
      - feature_engineering.lowercase
      - feature_engineering.stop_words
      - feature_engineering.ngram_range

    metrics:
      - reports/metrics.json

    outs:
      - artifacts/run_info.json

  model_register:
    cmd: python -m src.model.model_register

    deps:
      - artifacts/run_info.json
      - src/model/model_register.py